### ISSUE TITLE
Library not generating

### ISSUE THREAD

**Issue by BTopbas** [mancuniancol/script.subscription.quasar.imdb#3]
Hi;
Firstly thanks for your hard work for this scripts and providers. I used pulsar trakt subs and everything is fine. Now i use quasar and i know quasar have add to local library option but unfortunally this option not good as yours. (Example new tvshow and movies adding library 1 week later.) I love your imdb and trakt subs but i have problem with this. Movies is okey but TV Shows showing this.

![thumb_img_1274_1024](https://cloud.githubusercontent.com/assets/6390054/14776046/29c5a7e6-0acc-11e6-8478-f50b66314bfb.jpg)

![thumb_img_1275_1024](https://cloud.githubusercontent.com/assets/6390054/14776051/31f9e936-0acc-11e6-8b9b-09a6749be4aa.jpg)

No poster no seasons no info etc. My library not find tv shows but i can see tvshows added in folder. I can see strm files and if i click i successfully open with pulsar. No problem. But Library cant detect this. Trakt subs is same. I also tried imdb subs and same problem. What is problem ?

Edit: I update library. Scan Library. Reboot. Again add library. Clean Library. Changed Library folders(not forget change addon settings path) Regenerate etc. But always tvshows library not detected.

**Comment by mancuniancol** [comment]
Thank you for your message. To be honest, I was thinking to erase this code. I will check it. But, I think that it will be better to open the issue in Quasar to improve the library integration.

**Comment by BTopbas** [comment]
Yes you are right. Quasar library function is need to improve. But quasar looks like not alive. Last commit is very time ago..

**Comment by mancuniancol** [comment]
Good
